version: "3.9"
services:
  go-payment-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-payment-system
    depends_on:
      - go-payment-system-db
    env_file:
      - .env
    environment:
      DB_HOST: go-payment-system-db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - ${PORT}:${PORT}
    networks:
      - go-payment-system-network
    volumes:
      - ./db/migrations:/app/db/migrations
      - /app:/app

  go-payment-system-db:
    container_name: go-payment-system-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    image: postgres:14.2-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - go-payment-system-network
    ports:
      - "5432:5432"

volumes:
  pg-data:

networks:
  go-payment-system-network:
    driver: bridge